### PR TITLE
Support for earlier versions of Clojure

### PR DESCRIPTION
**Pull request by superstructor**
Clojure version in the core Pod (build.boot context) is not guaranteed
to be recent enough as Boot supports 1.6.0 onwards; therefore enable
support for using different versions of Clojure in the core Pod vs the
tools.deps Pod.

### CODE REVIEW

**Comment by seancorfield** [comment]
Clojure version uptake is pretty quick. Almost no one is on 1.6 at this point -- most folks are on 1.8 with 1.9 seeing quick uptake. I'm not willing to make this compromise for earlier versions. I'd rather force folks up to 1.9 at this point. But thanks for the PR!

**Comment by superstructor** [comment]
Although I agree almost no one is on 1.6 we are currently on 1.8. 

It’s not practical to be forced into immediately upgrading to 1.9 for hundreds of services running in a large production environment with massive numbers of users. We need to schedule and follow certain QA processes.

Please take a moment to reconsider including this patch as it is a blocking issue for us at the moment and would force me to fork our own copy, all of these contributions were aiming to avoid that. 

I would really appreciate it if you could include this change.

**Comment by seancorfield** [comment]
We've been running on 1.9 in production ever since the alphas so excuse me if I'm not very sympathetic :)

Although there is a 1.8 version of clj / clojure, my impression is that tools.deps is intended for 1.9+.

**Comment by superstructor** [comment]
I agree 1.9 is production ready and we have also been using it since the alphas, just not for every service. This is not a question of 1.9's production worthiness, rather it is a matter of change control and QA.

Many of our of services still use 1.8. These are all independent projects with their own repositories, releases, QA and JVM instances in production. It is simply not possible to simultaneously and immediately upgrade everything to 1.9. In some cases it can even cause compile errors with specs and require code modifications. 

`tools.deps` does work for resolving dependencies for 1.8 projects when running within a boot Pod. It tidies up the build with a standard idiomatic format and is one step closer to upgrading those projects to 1.9. I have tested it extensively, even before using and contributing to `boot-tools-deps`. It does not only have to be intended for 1.9+, it can also be on the path to 1.9!

Here you have a commercial active user happy to contribute development and testing to `boot-tools-deps`. Although 1.9 would be nice in theory, we have a real world requirement to maintain 1.8 projects. We would much prefer to contribute back to `boot-tools-deps` for the benefit of all users than maintain yet another internal project as a fork of this! 

What is your specific objection to my code ? Is there anything I could change to make it more suitable for merging ?

**Comment by seancorfield** [comment]
I think I was misunderstanding the context of what the change was actually trying to achieve but your latest comment makes it clear now, sorry.

**Comment by seancorfield** [comment]
Release 0.2.3 is on Clojars with this change.

**Comment by superstructor** [comment]
Thank you @seancorfield ! Much appreciated.

My apologies for not clarifying this in my initial pull request in the first instance.

**Pull request merged**
