### PR TITLE
Move pod forms to own ns

### PR DESCRIPTION
**Pull request by superstructor**
This is an initial draft. Need to add docstrings and fix at least one exception.

Why
* better IDE/editor experience
* easier to read

WIP: Need to fix java.lang.ClassNotFoundException: boot-tools-deps.pod

### CODE REVIEW

**Comment by seancorfield** [comment]
Ah yes, that is a nice improvement. Just needs a `require-in` call to bring that namespace into play I think. Do you want to finish the work before I merge, or shall I go ahead and merge this and finish the work myself?

**Comment by seancorfield** [comment]
Note: I think you'll find that trying to pass those deps into the pod as EDN (data structures), rather than strings, will fail -- that's why I switched to using the "unread" version of them both.

**Comment by superstructor** [comment]
All good thanks, I'm happy to finish it 👍 

My mistake was using `pod/with-eval-in` instead of `pod/with-call-in`.

Maybe I've hit the strings issue now, although I havn't had that issue in the past with pods and `with-call-in`. Will update after debugging.

**Comment by superstructor** [comment]
All fixed. Should be good to go now 👍 Thanks.

**Comment by seancorfield** [comment]
Given that the pod is being created from an environment that is already running the task, I don't think `boot-tools-deps` is needed as a dependency there -- I'll remove it and check it still works.

**Comment by superstructor** [comment]
Thanks for spotting that. Your correct it does appear to work without the `boot-tools-deps` dependency explicitly added to `pod-env`. I usually use less of the original environment in my pods so was done by habbit, apologies for that mistake.

**Comment by seancorfield** [comment]
Release 0.2.2 is up on Clojars.

**Pull request merged**
