### PR TITLE
Add :classifier support

### PR DESCRIPTION
**Pull request by superstructor**

### CODE REVIEW

**Comment by seancorfield** [comment]
This will be in 0.4.2 but I want to do a little housekeeping/cleanup before I release that.

**Comment by superstructor** [comment]
Thanks Sean! 👍 

The guide at https://clojure.org/reference/deps_and_cli#_dependencies also mentions `:extension` as an "optional key" but I have never used it so don't know it's purpose.

**Comment by seancorfield** [comment]
Looks like it indicates the file extension if it isn't `jar` -- which I would have expected to be `type`, but I should probably add that to the passthrough as well (note that `scope` isn't listed in the reference docs but is currently passed through as far as I can tell).

**Comment by superstructor** [comment]
`:scope` is definitely passed through, I use it regularly.

**Comment by seancorfield** [comment]
Well, modulo the discussion in #7 :)

**Comment by seancorfield** [comment]
Release 0.4.2 is on Clojars.

**Pull request merged**
